// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAfqS96cMrj6TFdpqNtfMwmxxeiSrG9Y8k',
    appId: '1:283187428602:web:95f4d69acbc3c034fbdd43',
    messagingSenderId: '283187428602',
    projectId: 'muiraquitabraille',
    authDomain: 'muiraquitabraille.firebaseapp.com',
    databaseURL: 'https://muiraquitabraille-default-rtdb.firebaseio.com',
    storageBucket: 'muiraquitabraille.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAJ6sWP3iripom1Qe5dLqpbpm_ACvOY0X4',
    appId: '1:283187428602:android:5f07dc6aba7c3846fbdd43',
    messagingSenderId: '283187428602',
    projectId: 'muiraquitabraille',
    databaseURL: 'https://muiraquitabraille-default-rtdb.firebaseio.com',
    storageBucket: 'muiraquitabraille.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC90oBcck-Sjdcg71TPmAHJ6d2i-EsxjVk',
    appId: '1:283187428602:ios:fa41b179149b19d1fbdd43',
    messagingSenderId: '283187428602',
    projectId: 'muiraquitabraille',
    databaseURL: 'https://muiraquitabraille-default-rtdb.firebaseio.com',
    storageBucket: 'muiraquitabraille.appspot.com',
    iosClientId: '283187428602-jjrkmgijheh2a2hdgpmm2fshouapfqr0.apps.googleusercontent.com',
    iosBundleId: 'com.example.brailleApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC90oBcck-Sjdcg71TPmAHJ6d2i-EsxjVk',
    appId: '1:283187428602:ios:fa41b179149b19d1fbdd43',
    messagingSenderId: '283187428602',
    projectId: 'muiraquitabraille',
    databaseURL: 'https://muiraquitabraille-default-rtdb.firebaseio.com',
    storageBucket: 'muiraquitabraille.appspot.com',
    iosClientId: '283187428602-jjrkmgijheh2a2hdgpmm2fshouapfqr0.apps.googleusercontent.com',
    iosBundleId: 'com.example.brailleApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAfqS96cMrj6TFdpqNtfMwmxxeiSrG9Y8k',
    appId: '1:283187428602:web:5c35b82ec166aad1fbdd43',
    messagingSenderId: '283187428602',
    projectId: 'muiraquitabraille',
    authDomain: 'muiraquitabraille.firebaseapp.com',
    databaseURL: 'https://muiraquitabraille-default-rtdb.firebaseio.com',
    storageBucket: 'muiraquitabraille.appspot.com',
  );
}
